# Generated by Django 2.2.7 on 2019-11-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('image_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('image_location', models.ImageField(upload_to='photos')),
                ('title', models.CharField(max_length=256)),
                ('shot_date', models.DateField()),
                ('max_prints', models.PositiveIntegerField()),
            ],
        ),
    ]
