# Generated by Django 2.2.7 on 2019-11-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('us_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('us_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                 to='geospatial.USAddress')),
            ],
        ),
    ]
