# Generated by Django 2.2.7 on 2019-11-10 00:22

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prints', '0001_initial'),
        ('customers', '0001_initial'),
        ('geospatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('order_status', enumfields.fields.EnumField(enum=orders.models.OrderStatus,
                                                             max_length=16)),
                ('customer', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL,
                                               to='customers.Customer')),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                            to='prints.Print')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                       to='geospatial.USAddress')),
            ],
        ),
    ]
